#!/usr/bin/env python3

def main():

    wordbank = ["indentation", "spaces"]

    tlgstudent = ["Aaron", "Andy", "Asif", "Brent", "Cedric", "Chris", "Cory", "Ebrima", "Franco", "Greg", "Hoon", "Joey", "Jordan", "JC", "LB", "Mabel", "Shon", "Pat", "Zach"]

    wordbank + int(4)

    int.num = input("choose between 0-18:")
    
    student_name = tlgstudent[num]

    print(student_name + "always uses")

main()
