#!/usr/bin/env python3
""" Alta3 Research | TPatrick -- tpatrick@alta3.com
    Review for class """

import os

def main():
        print("Hello World", "I'm Steve.", sep=" - ", end="\n\n")

        print(name)

        if name == "Ichabod":
            print("Congratulations! You have the best name!")
        elif name == "Felicity":
            print("Congratualtions! You have the best name!")
        else:
            print("You don't have the best naem. Sorry")

        print("Thanks for using this app, I guess.")

main()

